src/Entity/ItemsCollection.php
<?php

namespace App\Entity;

use App\Repository\ItemsCollectionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: ItemsCollectionRepository::class)]

#[UniqueEntity(
    fields: ['name', 'owner'],
    message: 'There is a collection with this name by this user.',
    errorPath: 'name',
)]
#[ORM\HasLifecycleCallbacks()]
class ItemsCollection
{
    use Timestamps;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'itemsCollections')]
    #[ORM\JoinColumn(nullable: false)]
    private $owner;


    #[ORM\ManyToOne(targetEntity: CollectionCategory::class, fetch: 'EAGER', inversedBy: 'collections')]
    #[ORM\JoinColumn(nullable: false)]
    private $Category;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $string_property_name_1;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $string_property_name_2;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $string_property_name_3;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $text_property_name_1;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $text_property_name_3;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $text_property_name_2;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $date_property_name_1;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $date_property_name_2;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $date_property_name_3;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $numeric_property_name_1;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $numeric_property_name_2;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $numeric_property_name_3;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $bool_property_name_1;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $bool_property_name_2;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $bool_property_name_3;

    #[ORM\OneToMany(mappedBy: 'parent_collection', targetEntity: Item::class, cascade: ["persist", "remove"], orphanRemoval: true)]
    private $items;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }



    public function getCategory(): ?CollectionCategory
    {
        return $this->Category;
    }

    public function setCategory(?CollectionCategory $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getStringPropertyName1(): ?string
    {
        return $this->string_property_name_1;
    }

    public function setStringPropertyName1(?string $string_property_name_1): self
    {
        $this->string_property_name_1 = $string_property_name_1;

        return $this;
    }

    public function getStringPropertyName2(): ?string
    {
        return $this->string_property_name_2;
    }

    public function setStringPropertyName2(?string $string_property_name_2): self
    {
        $this->string_property_name_2 = $string_property_name_2;

        return $this;
    }

    public function getStringPropertyName3(): ?string
    {
        return $this->string_property_name_3;
    }

    public function setStringPropertyName3(?string $string_property_name_3): self
    {
        $this->string_property_name_3 = $string_property_name_3;

        return $this;
    }

    public function getTextPropertyName1(): ?string
    {
        return $this->text_property_name_1;
    }

    public function setTextPropertyName1(?string $text_property_name_1): self
    {
        $this->text_property_name_1 = $text_property_name_1;

        return $this;
    }

    public function getTextPropertyName3(): ?string
    {
        return $this->text_property_name_3;
    }

    public function setTextPropertyName3(?string $text_property_name_3): self
    {
        $this->text_property_name_3 = $text_property_name_3;

        return $this;
    }

    public function getTextPropertyName2(): ?string
    {
        return $this->text_property_name_2;
    }

    public function setTextPropertyName2(?string $text_property_name_2): self
    {
        $this->text_property_name_2 = $text_property_name_2;

        return $this;
    }

    public function getDatePropertyName1(): ?string
    {
        return $this->date_property_name_1;
    }

    public function setDatePropertyName1(?string $date_property_name_1): self
    {
        $this->date_property_name_1 = $date_property_name_1;

        return $this;
    }

    public function getDatePropertyName2(): ?string
    {
        return $this->date_property_name_2;
    }

    public function setDatePropertyName2(?string $date_property_name_2): self
    {
        $this->date_property_name_2 = $date_property_name_2;

        return $this;
    }

    public function getDatePropertyName3(): ?string
    {
        return $this->date_property_name_3;
    }

    public function setDatePropertyName3(?string $date_property_name_3): self
    {
        $this->date_property_name_3 = $date_property_name_3;

        return $this;
    }

    public function getNumericPropertyName1(): ?string
    {
        return $this->numeric_property_name_1;
    }

    public function setNumericPropertyName1(?string $numeric_property_name_1): self
    {
        $this->numeric_property_name_1 = $numeric_property_name_1;

        return $this;
    }

    public function getNumericPropertyName2(): ?string
    {
        return $this->numeric_property_name_2;
    }

    public function setNumericPropertyName2(?string $numeric_property_name_2): self
    {
        $this->numeric_property_name_2 = $numeric_property_name_2;

        return $this;
    }

    public function getNumericPropertyName3(): ?string
    {
        return $this->numeric_property_name_3;
    }

    public function setNumericPropertyName3(?string $numeric_property_name_3): self
    {
        $this->numeric_property_name_3 = $numeric_property_name_3;

        return $this;
    }

    public function getBoolPropertyName1(): ?string
    {
        return $this->bool_property_name_1;
    }

    public function setBoolPropertyName1(?string $bool_property_name_1): self
    {
        $this->bool_property_name_1 = $bool_property_name_1;

        return $this;
    }

    public function getBoolPropertyName2(): ?string
    {
        return $this->bool_property_name_2;
    }

    public function setBoolPropertyName2(?string $bool_property_name_2): self
    {
        $this->bool_property_name_2 = $bool_property_name_2;

        return $this;
    }

    public function getBoolPropertyName3(): ?string
    {
        return $this->bool_property_name_3;
    }

    public function setBoolPropertyName3(?string $bool_property_name_3): self
    {
        $this->bool_property_name_3 = $bool_property_name_3;

        return $this;
    }

    public function getStringProperties(): ?array
    {
        return array_filter([
            $this->string_property_name_1,
            $this->string_property_name_2,
            $this->string_property_name_3,
            ]);
    }

    public function getTextProperties(): ?array
    {
        return array_filter([
            $this->text_property_name_1,
            $this->text_property_name_2,
            $this->text_property_name_3,
        ]);
    }

    public function getBoolProperties(): ?array
    {
        return array_filter([
            $this->bool_property_name_1,
            $this->bool_property_name_2,
            $this->bool_property_name_3,
        ]);
    }

    public function getNumericProperties(): ?array
    {
        return array_filter([
            $this->numeric_property_name_1,
            $this->numeric_property_name_2,
            $this->numeric_property_name_3,
        ]);
    }

    public function getDateProperties(): ?array
    {
        return array_filter([
            $this->date_property_name_1,
            $this->date_property_name_2,
            $this->date_property_name_3,
        ]);
    }

    /**
     * @return Collection|Item[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->setParentCollection($this);
        }

        return $this;
    }

    public function removeItem(Item $item): self
    {
        if ($this->items->removeElement($item)) {
            // set the owning side to null (unless already changed)
            if ($item->getParentCollection() === $this) {
                $item->setParentCollection(null);
            }
        }

        return $this;
    }
}

src/Controller/CollectionController.php
<?php

namespace App\Controller;

use App\Entity\ItemsCollection;
use App\Entity\User;
use App\Form\ItemsCollectionType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CollectionController extends AbstractController
{
    #[Route('/user/{id<\d+>}/collection/add', name: 'collection_add')]
    public function new(Request $request, EntityManagerInterface $entityManager, int $id): Response
    {
        $itemsCollection = new ItemsCollection();

        $itemsCollection->setOwner($entityManager->find('App:User', $id));

        $this->denyAccessUnlessGranted('COLLECTION_EDIT', $itemsCollection);

        $form = $this->createForm(ItemsCollectionType::class, $itemsCollection);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($itemsCollection);
            $entityManager->flush();
            return $this->redirectToRoute('collection_show', [
                'id' => $id,
                'collectionId' => $itemsCollection->getId()]);
        }

        return $this->renderForm('collection/add.html.twig', [
            'CollectionForm' => $form,
        ]);
    }

    #[Route('/user/{id<\d+>}/collection/{collectionId<\d+>}', name: 'collection_show')]
    public function show(Request $request, EntityManagerInterface $entityManager, int $collectionId)
    {
        $itemsCollection = $entityManager->find(ItemsCollection::class, $collectionId);
        if (!$itemsCollection) {
            throw $this->createNotFoundException(
                'There is no collection with id:' . $collectionId
            );
        }
        return $this->render('collection/show.html.twig', [
            'collection' => $itemsCollection,
        ]);


    }

    #[Route('/user/{id<\d+>}/collection/{collectionId<\d+>}/edit', name: 'collection_edit')]
    public function edit(Request $request, EntityManagerInterface $entityManager, int $collectionId, int $id): Response
    {

        $itemsCollection = $entityManager->find(ItemsCollection::class, $collectionId);


        if (!$itemsCollection) {
            throw $this->createNotFoundException(
                'There is no collection with id:' . $collectionId
            );
        }

        $this->denyAccessUnlessGranted('COLLECTION_EDIT', $itemsCollection);




        $form = $this->createForm(ItemsCollectionType::class, $itemsCollection);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($itemsCollection);
            $entityManager->flush();
            return $this->redirectToRoute('collection_show', ['id' => $id, 'collectionId' => $collectionId]);
        }
        return $this->renderForm('collection/edit.html.twig', [
            'CollectionForm' => $form,
            'collection' => $itemsCollection,
        ]);

    }

    #[Route('/user/{id<\d+>}/collection/{collectionId<\d+>}/remove', name: 'collection_remove')]
    public function delete(Request $request, EntityManagerInterface $entityManager, int $collectionId, int $id): Response
    {
        $itemsCollection = $entityManager->find('App:ItemsCollection', $collectionId);
        $this->denyAccessUnlessGranted('COLLECTION_EDIT', $itemsCollection);

        $agreement = $request->request->get('Delete_confirmation', 'No, Thanks');
        if(mb_strtolower($agreement) == 'i agree'){
            $entityManager->remove($itemsCollection);
            $entityManager->flush();
            return $this->redirectToRoute('user_profile', [
                'id' => $id,
            ]);

        }
        return $this->render('collection/delete.html.twig', [
            'id' => $id,
            'collectionId' => $collectionId,
            'collection' => $itemsCollection,
        ]);
    }

}

templates/collection/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create new collection{% endblock %}

{% block content %}
<div class="container-xl d-flex justify-content-center">
    {{ form_start(CollectionForm) }}
    <div class="d-flex align-items-start p-2">
        <div class="container overflow-hidden">
            <div class="row gx-5">

                {{ form_row(CollectionForm.name) }}
                {{ form_row(CollectionForm.Category) }}
            </div>
        </div>
    </div>
    <div class="d-flex align-items-start p-2">
        <div class="container overflow-hidden">
            <h5 class="row py-4">
            Custom string item properties:
            </h5>
            <div class="d-flex flex-row">
                <button class="btn btn-sm btn-primary" type="button" id="addString">Add Property</button>
            </div>
            <div class="row gx-5" id="stringProperties">

                {{ form_row(CollectionForm.string_property_name_1, { 'label': 'Custom string property #1' }) }}
                {{ form_row(CollectionForm.string_property_name_2, { 'label': 'Custom string property #2' }) }}
                {{ form_row(CollectionForm.string_property_name_3, { 'label': 'Custom string property #3' }) }}
            </div>

        </div>
    </div>
    <div class="d-flex align-items-start p-2">
        <div class="container overflow-hidden">
            <h5 class="row py-4">
                Custom text item properties:
            </h5>
            <div class="d-flex flex-row">
                <button class="btn btn-sm btn-primary" type="button" id="addText">Add Property</button>
            </div>
            <div class="row gx-5" id="textProperties">
                {{ form_row(CollectionForm.text_property_name_1, { 'label': 'Custom text property name #1' }) }}
                {{ form_row(CollectionForm.text_property_name_2, { 'label': 'Custom text property name #2' }) }}
                {{ form_row(CollectionForm.text_property_name_3, { 'label': 'Custom text property name #3' }) }}
            </div>
        </div>
    </div>
    <div class="d-flex align-items-start p-2">
        <div class="container overflow-hidden">
            <h5 class="row py-4">
                Custom numeric item properties:
            </h5>
            <div class="d-flex flex-row">
                <button class="btn btn-sm btn-primary" type="button" id="addNumeric">Add Property</button>
            </div>
            <div class="row gx-5" id="numericProperties">
                {{ form_row(CollectionForm.numericPropertyName1, { 'label': 'Custom numeric property name #1' }) }}
                {{ form_row(CollectionForm.numericPropertyName2, { 'label': 'Custom numeric property name #2' }) }}
                {{ form_row(CollectionForm.numericPropertyName3, { 'label': 'Custom numeric property name #3' }) }}
            </div>
        </div>
    </div>
    <div class="d-flex align-items-start p-2">
        <div class="container overflow-hidden">
            <h5 class="row py-4">
                Custom date item properties:
            </h5>
            <div class="d-flex flex-row">
                <button class="btn btn-sm btn-primary" type="button" id="addDate">Add Property</button>
            </div>
            <div class="row gx-5" id="dateProperties">
                {{ form_row(CollectionForm.datePropertyName1, { 'label': 'Custom date property name #1' }) }}
                {{ form_row(CollectionForm.datePropertyName2, { 'label': 'Custom date property name #2' }) }}
                {{ form_row(CollectionForm.datePropertyName3, { 'label': 'Custom date property name #3' }) }}
            </div>
        </div>
    </div>
    <div class="d-flex align-items-start p-2">
        <div class="container overflow-hidden">
            <h5 class="row py-4">
                Custom checkbox item properties:
            </h5>
            <div class="d-flex flex-row">
                <button class="btn btn-sm btn-primary" type="button" id="addBool">Add Property</button>
            </div>
            <div class="row gx-5" id="checkboxProperties">
                {{ form_row(CollectionForm.boolPropertyName1, { 'label': 'Custom checkbox property name #1' }) }}
                {{ form_row(CollectionForm.boolPropertyName2, { 'label': 'Custom checkbox property name #2' }) }}
                {{ form_row(CollectionForm.boolPropertyName3, { 'label': 'Custom checkbox property name #3' }) }}
            </div>
        </div>
    </div>
    <div class="d-flex align-items-start p-2">
        <div class="container overflow-hidden">
            {{ form_row(CollectionForm.description, { 'label': 'Collection description(use markdown', 'cols': '100', 'rows': '40' })  }}
        </div>
    </div>
    {{ form_rest(CollectionForm) }}
    {{ form_end(CollectionForm)}}
</div>
    <script>
        let strings = document.querySelector('#stringProperties').children;
        let texts = document.querySelector('#textProperties').children;
        let dates = document.querySelector('#dateProperties').children;
        let numerics = document.querySelector('#numericProperties').children;
        let checkboxes = document.querySelector('#checkboxProperties').children;
        let fields = [strings, texts, dates, numerics, checkboxes];
        for (let field of fields) {
            for (let child of field) {
                child.hidden = true;
            }
            field[0].hidden = false;
        }

        addString.onclick = ()=>processButton(strings);
        addText.onclick = ()=>processButton(texts);
        addDate.onclick = ()=>processButton(dates);
        addBool.onclick = ()=>processButton(checkboxes);
        addNumeric.onclick = ()=>processButton(numerics);


        function processButton(children) {
            for (let child of children) {
                console.log(child);
                if (child.hidden) {
                    child.hidden = false;
                    break;
                }
            }
        }

    </script>
{% endblock %}

templates/collection/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}Delete item {% endblock %}

{% block content %}
    <div class="px-4 py-5 my-5 text-center">
        <h5 class="display-6">Really delete collection {{ collection.name }}?</h5>
        <div class="col-lg-6 mx-auto">
            <p>Category of items: {{ collection.category.name }}</p>
            <p>Consists of {{ collection.items|length }} items</p>
            <p>
                Description
            </p>
            <p>
                {{ collection.description ?collection.description|markdown_to_html:'no description' }}
            </p>
            <small class="text-muted">added: {{ collection.getCreatedAt|date("d M Y", "Europe/Kiev")}}</small>
            <p class="mb-4">
            <form method="post" >
                <fieldset>
                    <div class="mb-3">
                        <label for="agreeDelete" class="form-label text-danger">Do you really agree to delete {{ collection.name }} including its items?</label>
                        <select id="agreeDelete" class="form-select" name="Delete confirmation">
                            <option>No, thanks</option>
                            <option>I agree</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </fieldset>
            </form>
            </p>

        </div>
    </div>

{% endblock %}

templates/collection/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit collection{{ collection.name }}{% endblock %}

{% block content %}
    <div class="container-xl d-flex justify-content-center">
        {{ form_start(CollectionForm) }}
        <div class="d-flex align-items-start p-2">
            <div class="container overflow-hidden">
                <div class="row gx-5">

                    {{ form_row(CollectionForm.name) }}
                    {{ form_row(CollectionForm.Category) }}
                </div>
            </div>
        </div>
        <div class="d-flex align-items-start p-2">
            <div class="container overflow-hidden">
                <h5 class="row py-4">
                    Custom string item properties:
                </h5>
                <div class="row gx-5" id="stringProperties">

                    {{ form_row(CollectionForm.string_property_name_1, { 'label': 'Custom string property #1' }) }}
                    {{ form_row(CollectionForm.string_property_name_2, { 'label': 'Custom string property #2' }) }}
                    {{ form_row(CollectionForm.string_property_name_3, { 'label': 'Custom string property #3' }) }}
                </div>

            </div>
        </div>
        <div class="d-flex align-items-start p-2">
            <div class="container overflow-hidden">
                <h5 class="row py-4">
                    Custom text item properties:
                </h5>
                <div class="row gx-5" id="textProperties">
                    {{ form_row(CollectionForm.text_property_name_1, { 'label': 'Custom text property name #1' }) }}
                    {{ form_row(CollectionForm.text_property_name_2, { 'label': 'Custom text property name #2' }) }}
                    {{ form_row(CollectionForm.text_property_name_3, { 'label': 'Custom text property name #3' }) }}
                </div>
            </div>
        </div>
        <div class="d-flex align-items-start p-2">
            <div class="container overflow-hidden">
                <h5 class="row py-4">
                    Custom numeric item properties:
                </h5>
                <div class="row gx-5" id="numericProperties">
                    {{ form_row(CollectionForm.numericPropertyName1, { 'label': 'Custom numeric property name #1' }) }}
                    {{ form_row(CollectionForm.numericPropertyName2, { 'label': 'Custom numeric property name #2' }) }}
                    {{ form_row(CollectionForm.numericPropertyName3, { 'label': 'Custom numeric property name #3' }) }}
                </div>
            </div>
        </div>
        <div class="d-flex align-items-start p-2">
            <div class="container overflow-hidden">
                <h5 class="row py-4">
                    Custom date item properties:
                </h5>
                <div class="row gx-5" id="dateProperties">
                    {{ form_row(CollectionForm.datePropertyName1, { 'label': 'Custom date property name #1' }) }}
                    {{ form_row(CollectionForm.datePropertyName2, { 'label': 'Custom date property name #2' }) }}
                    {{ form_row(CollectionForm.datePropertyName3, { 'label': 'Custom date property name #3' }) }}
                </div>
            </div>
        </div>
        <div class="d-flex align-items-start p-2">
            <div class="container overflow-hidden">
                <h5 class="row py-4">
                    Custom checkbox item properties:
                </h5>
                <div class="row gx-5" id="checkboxProperties">
                    {{ form_row(CollectionForm.boolPropertyName1, { 'label': 'Custom checkbox property name #1' }) }}
                    {{ form_row(CollectionForm.boolPropertyName2, { 'label': 'Custom checkbox property name #2' }) }}
                    {{ form_row(CollectionForm.boolPropertyName3, { 'label': 'Custom checkbox property name #3' }) }}
                </div>
            </div>
        </div>
        <div class="d-flex align-items-start p-2">
            <div class="container overflow-hidden">
                {{ form_row(CollectionForm.description, { 'label': 'Collection description(use markdown', 'cols': '100', 'rows': '40' })  }}
            </div>
        </div>
        <div class="d-flex align-items-start p-2">
        {{ form_rest(CollectionForm) }}
        </div>
    </div>
    <script>
        let inputs = document.querySelectorAll('input');
        for (let input of inputs) {
            if(!input.value){input.parentElement.hidden = true;}
        }
    </script>
{% endblock %}

templates/collection/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Collection{{ collection.name }}{% endblock %}

{% block content %}
    <main>
        <div class="container px-4 py-5">
            <h4 class="pb-2 border-bottom">Items of {{ collection.name}} by {{ collection.owner.name }}</h4>
            <div class="row g-4 py-5">
                {% for item in collection.items %}
                <div class="col-lg-3">
                    <h4>{{ item.name }}</h4>
                    <p>Part of collection: <a href="{{ path('collection_show', {'id': app.user.id, 'collectionId': collection.id}) }}" class="fs-5">{{ collection.name }}</a></p>
                    {% for stringField in item.stringFields %}
                        <p>{{ stringField.name}}: {{ stringField.data }}</p>
                    {% endfor %}
                    {% for numericField in item.numericFields %}
                        <p>{{ numericField.name}}: {{ numericField.data }}</p>
                    {% endfor %}
                    {% for dateField in item.dateFields %}
                        <p>{{ dateField.name}}: {{ dateField.data|date("d/m/Y") }}</p>
                    {% endfor %}
                    {% for textField in item.textFields %}
                        <p>{{ textField.name}}:</p>
                        <div>{{ textField.data|markdown_to_html }}</div>
                    {% endfor %}
                    <div class="d-flex justify-content-between align-items-center">
                        {% if app.user == collection.owner or is_granted('ROLE_ADMIN') %}
                        <div class="btn-group">
                            <a href="{{ path('item_edit', {'id': collection.owner.id, 'collectionId': collection.id, 'itemId': item.id}) }}" class="btn btn-sm btn-outline-dark">Edit</a>
                            <a href="#" class="btn btn-sm btn-outline-danger">Remove</a>
                        </div>
                        {% endif %}
                        <small class="text-muted">added: {{ item.getCreatedAt|date("d M Y", "Europe/Kiev")}}</small>
                    </div>
                </div>
                {% else %}
                    <h3>There are no items!</h3>
                    <div class="text-muted fs-5" > Maybe you want to <a href="{{ path('item_add', {'collectionId': collection.id, 'id': collection.owner.id}) }}" class="btn btn-primary">Add One</a></div>

                {% endfor %}


            </div>
        </div>
    </main>
{% endblock %}